/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as DashboardLabourRouteImport } from './routes/dashboard.labour'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardOwnerIndexRouteImport } from './routes/dashboard.owner.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardOwnerSubscriptionRouteImport } from './routes/dashboard.owner.subscription'
import { Route as DashboardOwnerSettingsRouteImport } from './routes/dashboard.owner.settings'
import { Route as DashboardOwnerReportsRouteImport } from './routes/dashboard.owner.reports'
import { Route as DashboardOwnerLabourRouteImport } from './routes/dashboard.owner.labour'
import { Route as DashboardOwnerHistoryRouteImport } from './routes/dashboard.owner.history'
import { Route as DashboardOwnerBuildingsRouteImport } from './routes/dashboard.owner.buildings'
import { Route as DashboardOwnerAssignTasksRouteImport } from './routes/dashboard.owner.assign-tasks'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminReportsRouteImport } from './routes/dashboard.admin.reports'
import { Route as DashboardAdminOwnersRouteImport } from './routes/dashboard.admin.owners'
import { Route as DashboardAdminLabourRouteImport } from './routes/dashboard.admin.labour'
import { Route as DashboardAdminEarningsRouteImport } from './routes/dashboard.admin.earnings'
import { Route as DashboardAdminChecklistsRouteImport } from './routes/dashboard.admin.checklists'
import { Route as DashboardAdminBuildingsRouteImport } from './routes/dashboard.admin.buildings'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLabourRoute = DashboardLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnerIndexRoute = DashboardOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardOwnerSubscriptionRoute =
  DashboardOwnerSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => DashboardOwnerRoute,
  } as any)
const DashboardOwnerSettingsRoute = DashboardOwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardOwnerReportsRoute = DashboardOwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardOwnerLabourRoute = DashboardOwnerLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardOwnerHistoryRoute = DashboardOwnerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardOwnerBuildingsRoute = DashboardOwnerBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => DashboardOwnerRoute,
} as any)
const DashboardOwnerAssignTasksRoute =
  DashboardOwnerAssignTasksRouteImport.update({
    id: '/assign-tasks',
    path: '/assign-tasks',
    getParentRoute: () => DashboardOwnerRoute,
  } as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReportsRoute = DashboardAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminOwnersRoute = DashboardAdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminLabourRoute = DashboardAdminLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminEarningsRoute = DashboardAdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminChecklistsRoute =
  DashboardAdminChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminBuildingsRoute = DashboardAdminBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/payment-result': typeof PaymentResultRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard/owner': typeof DashboardOwnerRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/buildings': typeof DashboardAdminBuildingsRoute
  '/dashboard/admin/checklists': typeof DashboardAdminChecklistsRoute
  '/dashboard/admin/earnings': typeof DashboardAdminEarningsRoute
  '/dashboard/admin/labour': typeof DashboardAdminLabourRoute
  '/dashboard/admin/owners': typeof DashboardAdminOwnersRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/owner/assign-tasks': typeof DashboardOwnerAssignTasksRoute
  '/dashboard/owner/buildings': typeof DashboardOwnerBuildingsRoute
  '/dashboard/owner/history': typeof DashboardOwnerHistoryRoute
  '/dashboard/owner/labour': typeof DashboardOwnerLabourRoute
  '/dashboard/owner/reports': typeof DashboardOwnerReportsRoute
  '/dashboard/owner/settings': typeof DashboardOwnerSettingsRoute
  '/dashboard/owner/subscription': typeof DashboardOwnerSubscriptionRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/owner/': typeof DashboardOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/payment-result': typeof PaymentResultRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/buildings': typeof DashboardAdminBuildingsRoute
  '/dashboard/admin/checklists': typeof DashboardAdminChecklistsRoute
  '/dashboard/admin/earnings': typeof DashboardAdminEarningsRoute
  '/dashboard/admin/labour': typeof DashboardAdminLabourRoute
  '/dashboard/admin/owners': typeof DashboardAdminOwnersRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/owner/assign-tasks': typeof DashboardOwnerAssignTasksRoute
  '/dashboard/owner/buildings': typeof DashboardOwnerBuildingsRoute
  '/dashboard/owner/history': typeof DashboardOwnerHistoryRoute
  '/dashboard/owner/labour': typeof DashboardOwnerLabourRoute
  '/dashboard/owner/reports': typeof DashboardOwnerReportsRoute
  '/dashboard/owner/settings': typeof DashboardOwnerSettingsRoute
  '/dashboard/owner/subscription': typeof DashboardOwnerSubscriptionRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/owner': typeof DashboardOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/payment-result': typeof PaymentResultRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard/owner': typeof DashboardOwnerRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/buildings': typeof DashboardAdminBuildingsRoute
  '/dashboard/admin/checklists': typeof DashboardAdminChecklistsRoute
  '/dashboard/admin/earnings': typeof DashboardAdminEarningsRoute
  '/dashboard/admin/labour': typeof DashboardAdminLabourRoute
  '/dashboard/admin/owners': typeof DashboardAdminOwnersRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/owner/assign-tasks': typeof DashboardOwnerAssignTasksRoute
  '/dashboard/owner/buildings': typeof DashboardOwnerBuildingsRoute
  '/dashboard/owner/history': typeof DashboardOwnerHistoryRoute
  '/dashboard/owner/labour': typeof DashboardOwnerLabourRoute
  '/dashboard/owner/reports': typeof DashboardOwnerReportsRoute
  '/dashboard/owner/settings': typeof DashboardOwnerSettingsRoute
  '/dashboard/owner/subscription': typeof DashboardOwnerSubscriptionRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/owner/': typeof DashboardOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/payment-result'
    | '/pricing'
    | '/product'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard/admin'
    | '/dashboard/labour'
    | '/dashboard/owner'
    | '/dashboard/'
    | '/dashboard/admin/buildings'
    | '/dashboard/admin/checklists'
    | '/dashboard/admin/earnings'
    | '/dashboard/admin/labour'
    | '/dashboard/admin/owners'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/settings'
    | '/dashboard/owner/assign-tasks'
    | '/dashboard/owner/buildings'
    | '/dashboard/owner/history'
    | '/dashboard/owner/labour'
    | '/dashboard/owner/reports'
    | '/dashboard/owner/settings'
    | '/dashboard/owner/subscription'
    | '/dashboard/admin/'
    | '/dashboard/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/demo'
    | '/login'
    | '/payment-result'
    | '/pricing'
    | '/product'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard/labour'
    | '/dashboard'
    | '/dashboard/admin/buildings'
    | '/dashboard/admin/checklists'
    | '/dashboard/admin/earnings'
    | '/dashboard/admin/labour'
    | '/dashboard/admin/owners'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/settings'
    | '/dashboard/owner/assign-tasks'
    | '/dashboard/owner/buildings'
    | '/dashboard/owner/history'
    | '/dashboard/owner/labour'
    | '/dashboard/owner/reports'
    | '/dashboard/owner/settings'
    | '/dashboard/owner/subscription'
    | '/dashboard/admin'
    | '/dashboard/owner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/payment-result'
    | '/pricing'
    | '/product'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard/admin'
    | '/dashboard/labour'
    | '/dashboard/owner'
    | '/dashboard/'
    | '/dashboard/admin/buildings'
    | '/dashboard/admin/checklists'
    | '/dashboard/admin/earnings'
    | '/dashboard/admin/labour'
    | '/dashboard/admin/owners'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/settings'
    | '/dashboard/owner/assign-tasks'
    | '/dashboard/owner/buildings'
    | '/dashboard/owner/history'
    | '/dashboard/owner/labour'
    | '/dashboard/owner/reports'
    | '/dashboard/owner/settings'
    | '/dashboard/owner/subscription'
    | '/dashboard/admin/'
    | '/dashboard/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PaymentResultRoute: typeof PaymentResultRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/labour': {
      id: '/dashboard/labour'
      path: '/labour'
      fullPath: '/dashboard/labour'
      preLoaderRoute: typeof DashboardLabourRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/owner/': {
      id: '/dashboard/owner/'
      path: '/'
      fullPath: '/dashboard/owner/'
      preLoaderRoute: typeof DashboardOwnerIndexRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/owner/subscription': {
      id: '/dashboard/owner/subscription'
      path: '/subscription'
      fullPath: '/dashboard/owner/subscription'
      preLoaderRoute: typeof DashboardOwnerSubscriptionRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/settings': {
      id: '/dashboard/owner/settings'
      path: '/settings'
      fullPath: '/dashboard/owner/settings'
      preLoaderRoute: typeof DashboardOwnerSettingsRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/reports': {
      id: '/dashboard/owner/reports'
      path: '/reports'
      fullPath: '/dashboard/owner/reports'
      preLoaderRoute: typeof DashboardOwnerReportsRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/labour': {
      id: '/dashboard/owner/labour'
      path: '/labour'
      fullPath: '/dashboard/owner/labour'
      preLoaderRoute: typeof DashboardOwnerLabourRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/history': {
      id: '/dashboard/owner/history'
      path: '/history'
      fullPath: '/dashboard/owner/history'
      preLoaderRoute: typeof DashboardOwnerHistoryRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/buildings': {
      id: '/dashboard/owner/buildings'
      path: '/buildings'
      fullPath: '/dashboard/owner/buildings'
      preLoaderRoute: typeof DashboardOwnerBuildingsRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/owner/assign-tasks': {
      id: '/dashboard/owner/assign-tasks'
      path: '/assign-tasks'
      fullPath: '/dashboard/owner/assign-tasks'
      preLoaderRoute: typeof DashboardOwnerAssignTasksRouteImport
      parentRoute: typeof DashboardOwnerRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/reports': {
      id: '/dashboard/admin/reports'
      path: '/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardAdminReportsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/owners': {
      id: '/dashboard/admin/owners'
      path: '/owners'
      fullPath: '/dashboard/admin/owners'
      preLoaderRoute: typeof DashboardAdminOwnersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/labour': {
      id: '/dashboard/admin/labour'
      path: '/labour'
      fullPath: '/dashboard/admin/labour'
      preLoaderRoute: typeof DashboardAdminLabourRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/earnings': {
      id: '/dashboard/admin/earnings'
      path: '/earnings'
      fullPath: '/dashboard/admin/earnings'
      preLoaderRoute: typeof DashboardAdminEarningsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/checklists': {
      id: '/dashboard/admin/checklists'
      path: '/checklists'
      fullPath: '/dashboard/admin/checklists'
      preLoaderRoute: typeof DashboardAdminChecklistsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/buildings': {
      id: '/dashboard/admin/buildings'
      path: '/buildings'
      fullPath: '/dashboard/admin/buildings'
      preLoaderRoute: typeof DashboardAdminBuildingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBuildingsRoute: typeof DashboardAdminBuildingsRoute
  DashboardAdminChecklistsRoute: typeof DashboardAdminChecklistsRoute
  DashboardAdminEarningsRoute: typeof DashboardAdminEarningsRoute
  DashboardAdminLabourRoute: typeof DashboardAdminLabourRoute
  DashboardAdminOwnersRoute: typeof DashboardAdminOwnersRoute
  DashboardAdminReportsRoute: typeof DashboardAdminReportsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBuildingsRoute: DashboardAdminBuildingsRoute,
  DashboardAdminChecklistsRoute: DashboardAdminChecklistsRoute,
  DashboardAdminEarningsRoute: DashboardAdminEarningsRoute,
  DashboardAdminLabourRoute: DashboardAdminLabourRoute,
  DashboardAdminOwnersRoute: DashboardAdminOwnersRoute,
  DashboardAdminReportsRoute: DashboardAdminReportsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardOwnerRouteChildren {
  DashboardOwnerAssignTasksRoute: typeof DashboardOwnerAssignTasksRoute
  DashboardOwnerBuildingsRoute: typeof DashboardOwnerBuildingsRoute
  DashboardOwnerHistoryRoute: typeof DashboardOwnerHistoryRoute
  DashboardOwnerLabourRoute: typeof DashboardOwnerLabourRoute
  DashboardOwnerReportsRoute: typeof DashboardOwnerReportsRoute
  DashboardOwnerSettingsRoute: typeof DashboardOwnerSettingsRoute
  DashboardOwnerSubscriptionRoute: typeof DashboardOwnerSubscriptionRoute
  DashboardOwnerIndexRoute: typeof DashboardOwnerIndexRoute
}

const DashboardOwnerRouteChildren: DashboardOwnerRouteChildren = {
  DashboardOwnerAssignTasksRoute: DashboardOwnerAssignTasksRoute,
  DashboardOwnerBuildingsRoute: DashboardOwnerBuildingsRoute,
  DashboardOwnerHistoryRoute: DashboardOwnerHistoryRoute,
  DashboardOwnerLabourRoute: DashboardOwnerLabourRoute,
  DashboardOwnerReportsRoute: DashboardOwnerReportsRoute,
  DashboardOwnerSettingsRoute: DashboardOwnerSettingsRoute,
  DashboardOwnerSubscriptionRoute: DashboardOwnerSubscriptionRoute,
  DashboardOwnerIndexRoute: DashboardOwnerIndexRoute,
}

const DashboardOwnerRouteWithChildren = DashboardOwnerRoute._addFileChildren(
  DashboardOwnerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardLabourRoute: typeof DashboardLabourRoute
  DashboardOwnerRoute: typeof DashboardOwnerRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardLabourRoute: DashboardLabourRoute,
  DashboardOwnerRoute: DashboardOwnerRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PaymentResultRoute: PaymentResultRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
